sudo: required
services:
- docker
language: node_js
node_js:
- '8'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - GH_REPO=moisbo/sails-hook-redbox-omero
  - GIT_NAME=DeploymentBot
  - GIT_EMAIL=deploy@travis-ci.org
  - secure: V7paUZSS4mgya31pEUZHj7t5gSPZZkfI494rSN/MBvqygg7V7ea18xcvvAM8pD7/HT/2zm81yKI8qtkAcctcWF5ZgH/r5HY4N5PWO2faX2JgDEDbUCTRVLTOkPPTeklEXuz/HKGVp0/UEGH35oMWP+EPWSvHQcL6BZmoRrF87QOlTluY20V7fUliGuGheVPNk7JCr2lhEQgdbB1MOQ/OZKrZ9+z1mOLOFT78/oULkpX6aIqKVvdvxMQj+ZeXl2SFBMUtEWEoCTfRjHG68B1Z60opwUoNIM3Ae3kTxh7MO6kZdEnYZnyNXqMvMCp8eHDG7F7qEcCtPBGeWyLERTQfBpMSPyu6FZHqkzpvs3en5VPn4nU2ywx1mijxy8B+d7a3SKiaFkzUGVPMOJel3VKlS+SuyywIE36KOHzFGkxnxvA+sAy4wvk6ADscFO3boPENDDlslUIYAa8U/ei7Lw3ZNS+BFclQuYnLyx+dL7+HLZGoJUzb8qjwDFeSgbeBq7ENyNT0XEdTv+s8p7PXwqVJahLijNy0Ehyj/sfLDr3NkXzAaqtpPFeFrhwIQglclxqRJntR6JrCeO9Aw+GGLGamSzv1T74cxR5/xQjRAJ05twVI7jxwyxRwQ8cXZaLuyi8qkW4U6ZZbK96oE0Dl/IZnP+UI7iBr0BFBSvyOf5swaIg=
install:
- npm install; cd app/omero; npm install; chmod +x buildAngularProd.sh; ./buildAngularProd.sh;
  cd -;
script: true
after_success:
- chmod +x deploySnapshotToBranch.sh; ./deploySnapshotToBranch.sh
